name: Azure Build container Workflow

on:
  workflow_run:
    workflows: [Azure Apply Workflow]
    types: [completed]
    branches: [main]

permissions:
  id-token: write
  contents: read

env:
  ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
  ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
  ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
  SLACK_BOT_TOKEN: "${{ secrets.SLACK_BOT_TOKEN }}"
  SLACK_APP_TOKEN: "${{ secrets.SLACK_APP_TOKEN }}"

jobs: 
  terraform-apply:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The triggering workflow passed'

      - name: Debug branch information
        run: |
          echo "Triggered by workflow: ${{ github.event.workflow_run.workflow_id }}"
          echo "Running on branch: ${{ github.event.workflow_run.head_branch }}"
          echo "Repository: ${{ github.repository }}"
          echo "Event name: ${{ github.event_name }}"
          echo "Workflow run conclusion: ${{ github.event.workflow_run.conclusion }}"

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            /*
            !/main.tf
            !/variables.tf

          sparse-checkout-cone-mode: false

      - name: Terraform install
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -reconfigure

      - name: Terraform Plan
        run: terraform plan -out "tfplan"
        timeout-minutes: 1

      - name: Convert Terraform Plan to JSON
        run: terraform show -json tfplan | grep '^{.*}$' > tfplan.json

      - name: Setup OPA
        uses: open-policy-agent/setup-opa@v2
        with:
          version: latest

      - name: Run OPA Authz Policy Check
        id: opa-authz-check
        run: |
          result=$(opa eval --data .github/workflows/terraform.rego --input tfplan.json "data.terraform.analysis.authz" --format=json | jq '.result[0].expressions[0].value')
          echo "result=$result" >> $GITHUB_ENV
          echo $result
        continue-on-error: false
      
      - name: Run OPA Score Policy Check
        id: opa-score-check
        run: |
          opa eval --data .github/workflows/terraform.rego --input tfplan.json "data.terraform.analysis.score"
        continue-on-error: false

      - name: Terraform Apply
        if: env.result == 'true'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_APP_TOKEN: ${{ secrets.SLACK_APP_TOKEN }}
        run: terraform apply -auto-approve

  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'