name: Azure Destroy Slack Bot Workflow

on:
  workflow_dispatch: # Allows the workflow to be triggered manually

# Special permissions required for OIDC authentication
permissions:
  id-token: write
  contents: read

# environment variables
env:
  ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
  ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
  ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
  SLACK_BOT_TOKEN: "${{ secrets.SLACK_BOT_TOKEN }}"
  SLACK_SIGNING_SECRET: "${{ secrets.SLACK_SIGNING_SECRET }}"
  NGROK_AUTHTOKEN: "${{ secrets.NGROK_AUTHTOKEN }}"

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Terraform install
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.9.8"

    - name: Login to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Set environment variables
      run: |
        echo "TF_VAR_azure_client_id=${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
        echo "TF_VAR_azure_tenant_id=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV
        echo "TF_VAR_azure_subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
        echo "TF_VAR_slack_bot_token_http=${{ secrets.SLACK_BOT_TOKEN }}" >> $GITHUB_ENV
        echo "TF_VAR_slack_app_token_http=${{ secrets.SLACK_SIGNING_SECRET }}" >> $GITHUB_ENV
        echo "TF_VAR_ngrok_authtoken=${{ secrets.NGROK_AUTHTOKEN }}" >> $GITHUB_ENV

    - name: Terraform Init
      run: terraform init
      working-directory: ./infra/parent_directory/

    - name: Terraform Plan
      run: terraform plan -out "tfplan"
      working-directory: ./infra/parent_directory/

    - name: Terraform Destroy
      run: terraform destroy -auto-approve -input=false
      working-directory: ./infra/parent_directory/
      