name: Azure Destroy Slack Bot Workflow

on:
  workflow_dispatch: # Allows the workflow to be triggered manually

# Special permissions required for OIDC authentication
permissions:
  id-token: write
  contents: read

# environment variables
env:
  ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
  ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
  ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          /*
          !/main.tf
        sparse-checkout-cone-mode: false

    - name: Terraform install
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -destroy

    - name: Terraform Destroy
      run: terraform destroy -auto-approve