name: Azure Destroy Slack Bot Workflow

on:
  workflow_dispatch: # Allows the workflow to be triggered manually

# Special permissions required for OIDC authentication
permissions:
  id-token: write
  contents: read

# environment variables
env:
  ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
  ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
  AZURE_CLIENT_SECRET: "${{ secrets.AZURE_CLIENT_SECRET }}"
  ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
  SLACK_BOT_TOKEN: "${{ secrets.SLACK_BOT_TOKEN }}"
  SLACK_APP_TOKEN: "${{ secrets.SLACK_APP_TOKEN }}"

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Terraform install
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: |
        terraform plan \
          -var="slack_bot_token=${{ secrets.SLACK_BOT_TOKEN }}" \
          -var="slack_app_token=${{ secrets.SLACK_APP_TOKEN }}" \
          -out "tfplan"
      timeout-minutes: 5

    - name: Terraform Destroy
      run: terraform destroy -auto-approve -input=false