name: Azure Plan Workflow

on:
  pull_request:
    # will target all branches except the below (only use branches or branches-ignore)
    branches:
      - main
     
    paths:
      # the workflow will only run if the below are changed
      - 'main.tf'

permissions:
  id-token: write
  contents: read

env:
  ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
  ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
  AZURE_CLIENT_SECRET: "${{ secrets.AZURE_CLIENT_SECRET }}"
  ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
  TF_VAR_slack_bot_token: "${{ secrets.SLACK_BOT_TOKEN }}"
  TF_VAR_slack_app_token: "${{ secrets.SLACK_APP_TOKEN }}"


jobs:
  terraform-plan-policy-check:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Terraform install
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init -reconfigure

    - name: Terraform Plan
      run: terraform plan -out "tfplan" -var="slack_app_token=${{ secrets.SLACK_APP_TOKEN }}" -var="slack_bot_token=${{ secrets.SLACK_BOT_TOKEN }}"

    - name: Convert Terraform Plan to JSON
      run: terraform show -json tfplan | grep '^{.*}$' > tfplan.json

    - name: Setup OPA
      uses: open-policy-agent/setup-opa@v2
      with:
        version: latest

    - name: Run OPA Authz Policy Check
      id: opa-authz-check
      run: |
        result=$(opa eval --data .github/workflows/terraform.rego --input tfplan.json "data.terraform.analysis.authz" --format=json | jq '.result[0].expressions[0].value')
        echo $result
      continue-on-error: false
    
    - name: Run OPA Score Policy Check
      id: opa-score-check
      run: opa eval --data .github/workflows/terraform.rego --input tfplan.json "data.terraform.analysis.score"
      continue-on-error: false


      
